### ISSUE TITLE
Player Schema

### ISSUE THREAD

**Issue by irfan-iiitr** [Mohitgit22/CSMS-Backend#1]
Issue: Design Player Schema and CRUD APIs
Description:
Create a MongoDB schema for players participating in multiple sports and design CRUD APIs to manage player data.

Schema Fields:
Name: String (required)
Year: Number (required)
Team: Object ID (reference to Team model, required)
Description: String
Phone Number: String
Social Media:
Facebook: String
Twitter: String
Instagram: String

Achievements: [sports , text ]

Required APIs (CRUD):
Create Player: POST /api/players
Read Player: GET /api/players/:id
Update Player: PUT /api/players/:id
Delete Player: DELETE /api/players/:id

**Comment by irfan-iiitr** [comment]
@Mohitgit22 anything else needed for players Schema?

**Comment by Mohitgit22** [comment]
I don't think so anything required is left
